export const IP256PluginDeployerAbi = [
    {
       type:"function",
       name:"executeAndDeployPasskey",
       inputs:[
          {
             name:"x",
             type:"uint256",
             internalType:"uint256"
          },
          {
             name:"y",
             type:"uint256",
             internalType:"uint256"
          },
          {
             name:"signerFactory",
             type:"address",
             internalType:"address"
          },
          {
             name:"calls",
             type:"tuple[]",
             internalType:"struct Call[]",
             components:[
                {
                   name:"target",
                   type:"address",
                   internalType:"address"
                },
                {
                   name:"value",
                   type:"uint256",
                   internalType:"uint256"
                },
                {
                   name:"data",
                   type:"bytes",
                   internalType:"bytes"
                }
             ]
          }
       ],
       outputs:[
          {
             name:"",
             type:"bytes[]",
             internalType:"bytes[]"
          }
       ],
       stateMutability:"nonpayable"
    }
 ]